#!/bin/bash

MAINCMD="$0"
FEEDLETTER_DIR="$(dirname $MAINCMD)"
EXECNAME="$(basename $MAINCMD)"

cd "$FEEDLETTER_DIR"

if [[ "$EXECNAME" == "feedletter-style" ]]; then
    FEEDLETTER_STYLE=true ./millw --no-server --watch runMainBackground PreMain "$@"
else
    echo "Expected this command to be 'feedletter-style'."
fi

