#!/bin/bash

# Choose between

#./millw --no-server runMainLocal PreMain "$@"
#./millw --no-server runMainBackground PreMain "$@"
#./millw --no-server runMain PreMain "$@"

# Style commands need to be run with the -w flag, but are managed
# by the separate script feedletter-style

# A bit (well, very) fragile...

MAINCMD="$0"
FEEDLETTER_DIR="$(dirname $MAINCMD)"
EXECNAME="$(basename $MAINCMD)"

cd "$FEEDLETTER_DIR"

if [[ "$1" == "--secrets" ]]; then
    SUBCMD="$3"
    FIRSTARG="$4"
else
    SUBCMD="$1"
    FIRSTARG="$2"
fi

if [[ "$EXECNAME" == "feedletter" ]]; then
    if [[ "$SUBCMD" == "edit-subscribable" ]]; then  # we need native streams...
        ./millw --no-server runMainLocal PreMain "$@"
    elif [[  "$SUBCMD" == "daemon" && "$FIRSTARG" == "--fork" ]]; then
        ./millw --no-server runMainBackground PreMain "$@"
    else
        ./millw --no-server runMain PreMain "$@"
    fi
else
    echo "Expected this command to be 'feedletter'."
fi


